services:
  backend:
    build: ./backend
    container_name: minimercado-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: minimercado-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
